platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-11-alpine}

inputs:
  - name: venue

outputs:
  - name: build-output

run:
  path: "cruiseline-venue/ci/tasks/build.sh"