platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: adoptopenjdk-11-alpine}

inputs:
  - name: cruiseline-venue

outputs:
  - name: build-output

run:
  path: "cruiseline-venue/ci/tasks/build.sh"