platform: linux

image_resource:
  type: docker-image
  source: {repository: adoptopenjdk/openjdk11, tag: x86_64-alpine-jdk-11.0.3_7}

inputs:
  - name: venues

outputs:
  - name: build-output

run:
  path: "venues/ci/tasks/build.sh"