platform: linux

image_resource:
  type: docker-image
  source: {repository: gcr.io/fe-mwright/cruiseline/tools, tag: latest}

inputs:
  - name: build-output

outputs:
  - name: build-output

run:
  path: "venue/ci/tasks/deploy-to-k8s.sh"