platform: linux

image_resource:
  type: docker-image
  source: 
    repository: mwrightregistry.azurecr.io/tools
    tag: latest
    username: ["((docker-username))"]
    password: ["((docker-password))"]

inputs:
  - name: venues

params:
  KUBECONFIG: 
  CONTEXT: 
  REGISTRY_USERNAME:
  REGISTRY_PASSWORD:

run:
  path: "venues/ci/tasks/kapp.sh"