platform: linux

image_resource:
  type: docker-image
  source: {repository: gcr.io/fe-mwright/cruiseline/pack, tag: latest}

params:
  GOOGLE_TOKEN:

inputs:
  - name: venue

outputs:
  - name: build-output

run:
  path: "venue/ci/tasks/pack.sh"