resources:
  - name: venue
    type: git
    check_every: 10s
    source:
      uri: https://github.com/mwright-pivotal/cruiseline-venues.git
      branch: master

  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: mwright@pivotal.io
      password: ((cf-password))
      organization: Southeast
      space: mwright
      skip_cert_check: false

jobs:
  - name: build
    public: true
    plan:
      - get: venue
        trigger: true
      - task: Build project
        file: venue/ci/tasks/build.yml
      - put: resource-deploy-web-app
        params:
          manifest: build-output/manifest.yml
          environment_variables:
            key: SPRING_DATA_USERNAME
            key2: mwright
