resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.14"

resources:
  - name: venue
    type: git
    check_every: 10s
    source:
      uri: https://github.com/mwright-pivotal/cruiseline-venues.git
      branch: master

#  - name: resource-deploy-web-app
#    type: kubernetes
#    source:
#      server: https://((master-ip)):8443
#      namespace: default
#      token: ((kubernetes-dev-token))
#      insecure_skip_tls_verify: true
jobs:
  - name: build
    public: true
    plan:
      - get: venue
        trigger: true
      - task: Build project
        privileged: true
        file: venue/ci/tasks/pack.yml
        params:
          GOOGLE_TOKEN: ((google-token))
          KUBE_CONFIG: ((kube-config))
          DOCKER_IMAGE: ((docker-image))
          DOCKER_USERNAME: ((docker-username))
          DOCKER_PASSWORD: ((docker-password))
          DOCKER_REGISTRY: ((docker-registry))
      - task: Deploy to Kubernetes
        file: venue/ci/tasks/deploy-to-k8s.yml
#      - put: resource-deploy-web-app
#        params:
#          kubectl: create -f build-output/deployment.yml
#          wait_until_ready_selector: app=venue
#          context: dev
#          kubeconfig_file: build-output/kube-config
